//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniCRM_EmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminSetting
    {
        public int SettingId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> AppoinTimeInterval { get; set; }
        public Nullable<System.DateTime> DailyEmailTime { get; set; }
        public Nullable<int> OverDueDaysRM { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
