//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniCRM_EmailService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OmniCRMEntities : DbContext
    {
        public OmniCRMEntities()
            : base("name=OmniCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminSetting> AdminSettings { get; set; }
        public virtual DbSet<AppoinmentStatusMaster> AppoinmentStatusMasters { get; set; }
        public virtual DbSet<AppointmentDetail> AppointmentDetails { get; set; }
        public virtual DbSet<CallDetail> CallDetails { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    }
}
